In [1]:
import pandas as pd

In [2]:
data= pd.read_csv('customer_shopping_behavior.csv.xls')

In [3]:
data

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 835.9 KB

In [6]:
data.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [8]:
data.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [20]:
data['Review Rating']=data.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [21]:
data.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [31]:
data.columns=data.columns.str.lower()

In [32]:
data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [33]:
data=data.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [34]:
data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [36]:
labels=['Young Adult','Adult','Middle-aged','Senior']
data['age_group']=pd.qcut(data['age'],q=4,labels=labels)

In [38]:
data[['age','age_group']].sample(10)

      age    age_group
2525   39        Adult
3592   61       Senior
27     56  Middle-aged
2106   60       Senior
1941   55  Middle-aged
2069   36        Adult
1897   53  Middle-aged
53     29  Young Adult
3549   44        Adult
463    37        Adult

In [40]:
# create column purchase frequency days  
frequency={
    'Fortnightly':14,
    'Weekly':7,
    'Annually':365,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Monthly':30,
    'Every 3 Months':90
}
data['purchase_frequency_days']=data['frequency_of_purchases'].map(frequency)

In [39]:
data['frequency_of_purchases'].unique()

<ArrowStringArray>
[   'Fortnightly',         'Weekly',       'Annually',      'Quarterly',
      'Bi-Weekly',        'Monthly', 'Every 3 Months']
Length: 7, dtype: str

In [43]:
data[['purchase_frequency_days','frequency_of_purchases']]

      purchase_frequency_days frequency_of_purchases
0                          14            Fortnightly
1                          14            Fortnightly
2                           7                 Weekly
3                           7                 Weekly
4                         365               Annually
...                       ...                    ...
3895                        7                 Weekly
3896                       14              Bi-Weekly
3897                       90              Quarterly
3898                        7                 Weekly
3899                       90              Quarterly

[3900 rows x 2 columns]

In [44]:
data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchase_frequency_days'],
      dtype='str')

In [46]:
(data['discount_applied']==data['promo_code_used']).all()

np.True_

In [47]:
data=data.drop(columns=['promo_code_used'])

In [48]:
data

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,Weekly,Adult,7
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,Bi-Weekly,Middle-aged,14
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,Quarterly,Middle-aged,90
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,Weekly,Adult,7
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,Quarterly,Middle-aged,90

In [49]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.13-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.1.4-cp313-cp313-win_amd64.whl.metadata (9.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\shankar dixit\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (4.12.2)
Downloading psycopg2_binary-2.9.13-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 351.1 kB/s eta 0:00:07
   ------- -------------------------------- 0.5/2.8 MB 351.1 kB/s eta 0:00:07
   ------- -------------------------------- 0.5/2.8 MB 351.1 kB/s eta 0:00:07
   ----------- ---------------------------- 0.8/2.8 MB 409.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.8/2.8 MB 409.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.8/2.8 MB 409.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.8/2.8 MB 409.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.8/2.8 MB 409.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.8/2.8 MB 409.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.8/2.8 MB 409.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.8/2.8 MB 409.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.8/2.8 MB 409.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.8/2.8 MB 409.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.8/2.8 MB 409.7 kB/s eta 0:00:05
   --------------- ------------------------ 1.0/2.8 MB 218.0 kB/s eta 0:00:08
   ------------------ --------------------- 1.3/2.8 MB 271.7 kB/s eta 0:00:06
   ------------------ --------------------- 1.3/2.8 MB 271.7 kB/s eta 0:00:06
   ---------------------- ----------------- 1.6/2.8 MB 313.7 kB/s eta 0:00:04
   -------------------------- ------------- 1.8/2.8 MB 354.1 kB/s eta 0:00:03
   ------------------------------ --------- 2.1/2.8 MB 391.8 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.8 MB 418.3 kB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.8 MB 418.3 kB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.8 MB 418.3 kB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.8 MB 418.3 kB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 425.7 kB/s  0:00:06
Downloading sqlalchemy-2.1.4-cp313-cp313-win_amd64.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.4 MB 1.4 MB/s eta 0:00:02
   ------------ --------------------------- 0.8/2.4 MB 71.1 kB/s eta 0:00:24
   ----------------- ---------------------- 1.0/2.4 MB 103.7 kB/s eta 0:00:14
   ----------------- ---------------------- 1.0/2.4 MB 103.7 kB/s eta 0:00:14
   --------------------- ------------------ 1.3/2.4 MB 129.4 kB/s eta 0:00:09
   ------------------------- -------------- 1.6/2.4 MB 159.1 kB/s eta 0:00:06
   ------------------------------ --------- 1.8/2.4 MB 184.7 kB/s eta 0:00:04
   ---------------------------------------- 2.4/2.4 MB 246.3 kB/s  0:00:09
Installing collected packages: sqlalchemy, psycopg2-binary

   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   ---------------------------------------- 2/2 [psycopg2-binary]

Successfully installed psycopg2-binary-2.9.13 sqlalchemy-2.1.4
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\shankar dixit\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\shankar dixit\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\shankar dixit\AppData\Local\Programs\Python\Python313\Lib\site-packages)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [50]:
!pip install mysql-connector-python pymysql pandas

Requirement already satisfied: mysql-connector-python in C:\Users\shankar dixit\AppData\Local\Programs\Python\Python313\Lib\site-packages (9.2.0)
Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: pandas in C:\Users\shankar dixit\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\shankar dixit\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\shankar dixit\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\shankar dixit\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in C:\Users\shankar dixit\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\shankar dixit\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\shankar dixit\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\shankar dixit\AppData\Local\Programs\Python\Python313\Lib\site-packages)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [53]:
import mysql.connector


# Establish the connection
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="292005",
    database="customer_behavior"
)

print("Connection successful!" if conn.is_connected() else "Connection failed.")

Connection successful!

In [54]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in C:\Users\shankar dixit\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.1.4)
Requirement already satisfied: pymysql in C:\Users\shankar dixit\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.2.3)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\shankar dixit\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (4.12.2)

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\shankar dixit\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\shankar dixit\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\shankar dixit\AppData\Local\Programs\Python\Python313\Lib\site-packages)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [56]:
from sqlalchemy import create_engine

# 1. Create a SQLAlchemy engine using your credentials
# Syntax: mysql+pymysql://user:password@host:port/database
engine = create_engine("mysql+pymysql://root:292005@localhost:3306/customer_behavior")

# 2. Transfer the DataFrame to MySQL Workbench
# Replace 'your_dataframe' with your actual DataFrame variable
data.to_sql(
    name='customer', 
    con=engine, 
    if_exists='fail',          # Options: 'fail', 'replace', or 'append'
    index=False                # Set to True if you want to keep the index column
)

print("Dataset successfully transferred to MySQL Workbench!")

Dataset successfully transferred to MySQL Workbench!